logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.william: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gpsdata
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  jackson:
    serialization:
      write-dates-as-timestamps: true
